### ISSUE TITLE
Feature Request:  Allow tests to have names and display them on failure

### ISSUE THREAD

**Issue by jgc94131** [Orange-OpenSource/hurl#1067]
When running `hurl` in test mode, you can see the line number and assertion failures but it would be great to be able to display a test name as well.  

Now:
```
% hurl --test tests.hurlfile
tests.hurlfile: Running [1/1]
error: Assert status code
  --> tests.hurlfile:73:10
   |
73 | HTTP/1.1 200
   |          ^^^ actual value is <404>
   |
```

Enhanced:
```
% hurl --test tests.hurlfile
tests.hurlfile: Running [1/1]
test: POST to /foobar with good request
error: Assert status code
  --> tests.hurlfile:73:10
   |
73 | HTTP/1.1 200
   |          ^^^ actual value is <404>
   |

```

**Comment by ad8lmondy** [comment]
I asked for something similar in here: https://github.com/Orange-OpenSource/hurl/issues/1044 (though an explicit 'name' might be cool too)

The solution I went with was to use a comment after the assertion, as that gets printed out with the error.

**Comment by jcamiel** [comment]
Hi, 
Unfortunately, we don't have any metadata in the Hurl file format, and, for the moment, we don't have such things in our plan. You can still use we [HTML report](https://hurl.dev/docs/manual.html#report-html), [JUnit report](https://hurl.dev/docs/manual.html#report-html) (and soon [TAP report](https://github.com/Orange-OpenSource/hurl/issues/921)), or [JSON output](https://hurl.dev/docs/manual.html#json) to do a custom output if you want something tailored to your needs...

**Comment by jgc94131** [comment]
This isn't a new pattern.  So what I'm suggesting has precedent.  When writing table driven unit tests we always provide a "msg" column in the table which the testing framework gladly lets us display on failure.  It helps a lot. 

* https://dave.cheney.net/2019/05/07/prefer-table-driven-tests

 Maybe we can find a way to add this to the backlog?

**Comment by jcamiel** [comment]
I understand the use case. Do you need something for every request of a Hurl file (there can be a chain of requests), or a unique description for the whole file is sufficient? In the latter case, a possibility is to have either : 

- a custom header [Front Matter like](https://jekyllrb.com/docs/front-matter/):

~~~
---
description: Check that health check format is correct
enabled: true
---

GET https://foo.com
HTTP/2 200

GET https://bar.com
HTTP/2 200
~~~

- a comment header with conventional format:

~~~
# Description: Check that health check format is correct
# other comments not part of th description

GET https://foo.com
HTTP/2 200

GET https://bar.com
HTTP/2 200
~~~

Just asking for input and not commiting for delivery!

**Comment by jgc94131** [comment]
I don't need [msg] on every request, but on every test 'block'.  The same would be for each [assert] line, I don't really want to have a [msg] for each assert.    My ideal use case would be to have 1 hurl file, with dozens of tests, run in the order in which they appear.  Upon failure, the [msg] would be printed along with the failure details.  This would keep tests together, in a small (1?) number of files, and provide contextual failure status. 

I'm happy to contribute to this btw.

**Comment by dnsmichi** [comment]
@jcamiel One workaround I found within GitLab CI/CD was manually replacing the JUnit test report with the `id` field becoming the `name` field. That allows the GitLab test integration to render the 

When using files to instruct hurl to run, this works very well to see which file name failed the hurl test runs. 

The tricky part was to convince the shell runner to not exit early when the report failed, then modify the XML with sed, and then call exit based on the previous response. Not beautiful, so I would appreciate a boring solution with passing `id` and `name` as fields with the same value into the JUnit XML report. 

If there is no `id` because there is no file, a string identifier that gets passed as `--id` parameter could be an option. 

```yaml
# Hurl job template
.hurl-tmpl:
    image: registry.gitlab.com/everyonecancontribute/dev/hurl-playground:latest
    variables:
        HURL_URL: gitlab.com
        HURL_JUNIT_REPORT: hurl_junit_report.xml

# Hurl tests from configuration file, generating JUnit report integration in GitLab CI/CD
hurl-report:
    extends: .hurl-tmpl
    script:
      # Hack: Workaround for 'id' instead of 'name' in JUnit report from Hurl. https://gitlab.com/gitlab-org/gitlab/-/issues/299086 and do not fail early,https://stackoverflow.com/a/70087560/1821348
      - set +e +o pipefail
      - hurl --test use-cases/*.hurl --report-junit $HURL_JUNIT_REPORT; result=$?; sed -i 's/id/name/g' $HURL_JUNIT_REPORT
      - set -e -o pipefail
      - "[ $result == 0 ]"
    artifacts:
      when: always
      paths:
        - $HURL_JUNIT_REPORT
      reports:
        junit: $HURL_JUNIT_REPORT
```

Example pipeline run in https://gitlab.com/everyonecancontribute/dev/hurl-playground/-/merge_requests/10 which uses the following configuration file https://gitlab.com/everyonecancontribute/dev/hurl-playground/-/blob/4bb522da0ccfd1e8716b66dad97eb04eff8aacf5/use-cases/opsindev-news.hurl 

```
GET https://opsindev.news

# This will fail on purpose 
HTTP/1.1 200

[Asserts]
body contains "Michael Friedrich"
```

![image](https://user-images.githubusercontent.com/382049/206551483-479713d0-d892-4a45-9ff4-8f47b75e8312.png)

**Comment by jcamiel** [comment]
@dnsmichi We haven't work a lot on the JUnit report so any improvement is welcome. Integrated seamlessly in GitLab CI/CD is a really good use case. For the next release (should be released at the beginning of January), we can, at minimum, add the `name` attribute (using same value as `id`) and give us more time to think on a solution to pass explicitly a "name" or a "description" to a Hurl test file.  I don't know if there an authoritative source for the Junit file format but we can also improve it ([here](https://www.ibm.com/docs/en/developer-for-zos/16.0?topic=formats-junit-xml-format) I can see that `tests` and `failures` attributes exists also).

**Comment by jgc94131** [comment]
I think ```JUnit``` reporting might be the best way to approach this.   From the JUnit5 docs:

```
6.1.2. Open Test Reporting XML format
[OpenTestReportGeneratingListener](https://junit.org/junit5/docs/current/api/org.junit.platform.reporting/org/junit/platform/reporting/open/xml/OpenTestReportGeneratingListener.html) writes an XML report for the entire execution in the event-based format specified by [Open Test Reporting](https://github.com/ota4j-team/open-test-reporting) which supports all features of the JUnit Platform such as hierarchical test structures, display names, tags, etc.
```

Support for something akin to the JUnit @DisplayName annotation as described is exactly what I think would be great.

**Comment by dnsmichi** [comment]
My gut feeling is that a `name` attribute for tests will solve multiple problems:

1) Clearly communicate which test failed, and allow folks who are on-call / responsible to take action without looking at long lists. `name` could end up in an external tool's URL.
2) Single source of truth for JUnit reports, JSON data, XML data format. 
3) If `name` is not specified, use the filename as fallback. If the test was passed on the CLI, a `--name` parameter can help solve the null problem. 

`name` could also be auto-generated if not specified, e.g. combining the `GET https://example.org/news` into a string that reads `get-https-example-org-news`. Not sure though if that's worth the effort - there's always duplicates and problems with trying to generate and guess IDs when not specified. 

From a DSL perspective, all actions are described in `[]` brackets. Adding `[Config]` as a section helps with `name` and opens the possibility to add additional future attributes. (thinking out loud here, I had been designing a DSL in my past OSS project that lasted 8+ years).

```
POST https://example.org/contact
[FormParams]
default: false
token: {{token}}
email: john.doe@rookie.org
number: 33611223344

[Config]
name: example-org-contact
```

**Comment by didier-contribs** [comment]
+1 for names on each test

(in the ansible world each action has a name and it's very useful, in python testing there's also this notion of one test one name)

BTW bravo for hurl, it's so nice

**Comment by dnsmichi** [comment]
I've written a longer blog post about using Hurl in GitLab CI/CD, which also links here and the great discussion leading to features. https://about.gitlab.com/blog/2022/12/14/how-to-continously-test-web-apps-apis-with-hurl-and-gitlab-ci-cd/ 

For Hurl 1.8.0, I've documented a workaround using `after_script` to modify the JUnit report artifact when used with GitLab CI/CD, copying here: 

```yaml
# Hurl job template
.hurl-tmpl:
    image: registry.gitlab.com/everyonecancontribute/dev/hurl-playground:latest
    variables:
        HURL_URL: gitlab.com
        HURL_JUNIT_REPORT: hurl_junit_report.xml

# Hurl tests from configuration file, generating JUnit report integration in GitLab CI/CD
hurl-report:
    extends: .hurl-tmpl
    script:
      - hurl --test use-cases/*.hurl --report-junit $HURL_JUNIT_REPORT
    after_script:
      # Hack: Workaround for 'id' instead of 'name' in JUnit report from Hurl. https://gitlab.com/gitlab-org/gitlab/-/issues/299086
      - sed -i 's/id/name/g' $HURL_JUNIT_REPORT
    artifacts:
      when: always
      paths:
        - $HURL_JUNIT_REPORT
      reports:
        junit: $HURL_JUNIT_REPORT
```
