### ISSUE TITLE
Public docker image

### ISSUE THREAD

**Issue by danjamesmay** [Orange-OpenSource/hurl#266]
Hi,

This looks like a really cool tool, but it would be great if there was an official docker image published to docker hub or similar.

**Comment by fabricereix** [comment]
Thanks fors your suggestion.
Indeed, that could be useful to some people.
We will add it to docker hub.

**Comment by danjamesmay** [comment]
> > This looks like a really cool tool, but it would be great if there was an official docker image published to docker hub or similar.
> 
> I'm a big docker user. But I was wondering, what is your use case for this? Just curious!

I tend to run CLI tools in a docker wrapper, so I can have a standard environment locally and in CI. By standard environment I mean configured the same way, and the same version of dependencies.

**Comment by danjamesmay** [comment]
Sure. An example of how I wrap another cli app (Terraform in this case):

```
services:
  terraform-wrapper:
    image: hashicorp/terraform:1.0.6
    environment:
      - TF_WORKSPACE=$ENVIRONMENT
      - TF_IN_AUTOMATION=1
    volumes:
      - ${PWD}:/terraform
    working_dir: /terraform
    entrypoint: sh -c # default is `terraform` for image
```

Then run with: `docker-compose run --rm terraform-wrapper "terraform version"`
