### ISSUE TITLE
Run entry when it matches some condition?

### ISSUE THREAD

**Issue by iredmail** [Orange-OpenSource/hurl#3300]
### Problem to solve

Our application supports MySQL and OpenLDAP backend, there're few differences between them, we'd like to run certain hurl entries when it's using X backend.

I didn't find a solution in hurl document.

### Proposal

Is it possible to add such condition support? Like Ansible, use `when:`: https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_conditionals.html#basic-conditionals-with-when
```
tasks:
  - name: Shut down Debian flavored systems
    ansible.builtin.command: /sbin/shutdown -t now
    when: ansible_facts['os_family'] == "Debian"
```

And hurl:
```
POST {{server}}/domain/abc.io
WHEN: my_variable=my_value

HTTP 200
[Asserts]
...
```
