### ISSUE TITLE
Support more platforms in orangeopensource/hurl Docker image

### ISSUE THREAD

**Issue by humphd** [Orange-OpenSource/hurl#536]
I'm using hurl on an M1 Mac, and using the Docker image assumes I'm on `amd64`:

```sh
$ docker run --rm orangeopensource/hurl --version
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
hurl 1.6.1 libcurl/7.81.0-DEV OpenSSL/1.1.1n zlib/1.2.12
```

I can get around it by explicitly opting into the `amd64` arch:

```sh
$ docker run --platform=linux/amd64 --rm orangeopensource/hurl --version
hurl 1.6.1 libcurl/7.81.0-DEV OpenSSL/1.1.1n zlib/1.2.12
```

But it would be great if the image was built for more `--platform`s, especially `linux/arm64/v8`.  I don't know about the Rust part, but doing this in the Dockerfile is a matter of:

```Dockerfile
FROM --platform=${BUILDPLATFORM} alpine:3.15 AS builder
...
FROM --platform=${BUILDPLATFORM} alpine:3.15 AS runner
```

Then when you build using `buildx`, you can specify your platform(s), see https://docs.docker.com/buildx/working-with-buildx/#build-multi-platform-images.  Your base images (alpine) already do this, so it will just work.

Automating this in CI would look something like:

```yaml
jobs:
  docker:
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: docker/build-push-action@v2
        env:
          DOCKER_REPO: orangeopensource/hurl
          VERSION_TAG: ${{ github.ref_name }}
          SHA_TAG: sha-${{ github.sha }}
        with:
          context: .
          platforms: linux/amd64, linux/arm64v8 # add others as desired
          tags: ${{ env.DOCKER_REPO }}:${{ env.VERSION_TAG }}, ${{ env.DOCKER_REPO }}:${{ env.SHA_TAG }}, ${{ env.DOCKER_REPO }}:latest
          push: true
```

This could be done on every `release` or `tag` event.
